# Generated by Django 4.0.1 on 2022-01-11 06:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)])),
                ('ocupado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'asiento',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'bus',
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'chofer',
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.asiento')),
            ],
            options={
                'db_table': 'pasajero',
            },
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('lugar_partida', models.CharField(max_length=50)),
                ('lugar_llegada', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'trayecto',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.bus')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.pasajero')),
                ('trayecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.trayecto')),
            ],
            options={
                'db_table': 'viaje',
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='chofer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plataforma.chofer'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.bus'),
        ),
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('numero', 'bus')},
        ),
    ]
