# Generated by Django 4.0.1 on 2022-01-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='chofer',
        ),
        migrations.DeleteModel(
            name='Chofer',
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='asiento',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='pasajero',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='trayecto',
        ),
        migrations.DeleteModel(
            name='Asiento',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Pasajero',
        ),
        migrations.DeleteModel(
            name='Trayecto',
        ),
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
