# Generated by Django 4.0.1 on 2022-01-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='bus',
            field=models.BigIntegerField(),
        ),
    ]
