# Generated by Django 4.0.1 on 2022-01-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='id',
        ),
        migrations.AddField(
            model_name='bus',
            name='placa',
            field=models.CharField(default=3234, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
