# Generated by Django 4.0.1 on 2022-01-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_asiento_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='asiento',
        ),
    ]
