# Generated by Django 4.0.1 on 2022-01-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_remove_pasajero_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='asiento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='plataforma.asiento'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='viaje',
            unique_together={('pasajero', 'asiento'), ('pasajero', 'trayecto')},
        ),
    ]
