# Generated by Django 4.0.1 on 2022-01-09 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_alter_asiento_table_alter_bus_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='chofer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plataforma.chofer'),
        ),
    ]
