# Generated by Django 4.0.1 on 2022-01-11 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_viaje_asiento_alter_viaje_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='bus',
        ),
        migrations.AddField(
            model_name='trayecto',
            name='bus',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='plataforma.bus'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='trayecto',
            unique_together={('horario', 'bus')},
        ),
    ]
