# Generated by Django 4.0.1 on 2022-01-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_remove_viaje_bus_trayecto_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='apellido',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
